name: Deploy Angular to GitHub Pages

# Trigger do workflow
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
    types: [closed]

# Permissões necessárias para deploy no GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Concorrência - cancela execuções anteriores se houver nova
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job de Build e Test
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless

    - name: Run linting (if available)
      run: |
        if npm list @angular-eslint/eslint-plugin >/dev/null 2>&1; then
          npm run lint
        else
          echo "Linting not configured, skipping..."
        fi
      continue-on-error: true

    - name: Build for production (SPA mode)
      run: npm run build -- --configuration spa --base-href /sistema-siseja-frontend/

    # NOVO PASSO: Renomeia o index.csr.html para index.html
    - name: Rename index file for GitHub Pages
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
      run: |
        if [ -f "./dist/sistema-siseja-frontend/browser/index.csr.html" ]; then
          mv ./dist/sistema-siseja-frontend/browser/index.csr.html ./dist/sistema-siseja-frontend/browser/index.html
          echo "✅ Renamed index.csr.html to index.html"
        else
          echo "❌ index.csr.html not found, skipping rename."
        fi

    - name: Create 404.html for SPA routing
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
      run: |
        if [ -f "./dist/sistema-siseja-frontend/browser/index.html" ]; then
          cp ./dist/sistema-siseja-frontend/browser/index.html ./dist/sistema-siseja-frontend/browser/404.html
          echo "✅ Created 404.html from index.html"
        else
          echo "❌ index.html not found, cannot create 404.html."
        fi

    - name: Setup Pages
      uses: actions/configure-pages@v4
      with:
        enablement: true
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
      with:
        # Upload o conteúdo da pasta 'browser' que contém o index.html
        path: './dist/sistema-siseja-frontend/browser'

  # Job de Deploy (só executa na branch master/main)
  deploy:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    needs: build-and-test
    runs-on: ubuntu-latest
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

  # Job para notificação de status (opcional)
  notify-status:
    needs: [build-and-test, deploy]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Notify deployment success
      if: needs.deploy.result == 'success'
      run: |
        echo "✅ Deploy realizado com sucesso!"
        echo "🚀 Aplicação disponível em: ${{ needs.deploy.outputs.url }}"
    
    - name: Notify deployment failure
      if: needs.deploy.result == 'failure'
      run: |
        echo "❌ Falha no deploy"
        exit 1